### PR TITLE
added fix based on the dev commin in Automatic1111

### LINKED ISSUE #6: Scripts are currently broken
The main script in Automatic1111 repo https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/scripts/prompts_from_file.py is broken, and so are these scripts. Fix is in the #5

### PR DESCRIPTION
**Pull request by racinmat**
Currently these scripts are broken, because the original script in https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/scripts/prompts_from_file.py is broken too. The Automatic1111 made a fix to the dev branch, so I copied the contents here https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/483545252f865334a6da84339126cefd59c3d885

I also refactored the shared code out to the script_common.py, because the code is duplicated.

Fixes #6

### CODE REVIEW

**Comment by racinmat** [comment]
ping @Z-nonymous

**Comment by Trevor-Z** [comment]
Should the extension work be working again after this merge?

**Comment by racinmat** [comment]
Yes, it should is anything broken there?

**Comment by Trevor-Z** [comment]
I filed an issue: https://github.com/Z-nonymous/sd_webui_batchscripts/issues/7

**Pull request merged**
